site1/site1/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
	path('', views.index, name = "index"),
	path('<int:article_id>/', views.detail, name = "detail"),
	path('<int:article_id>/leave_comment', views.leave_comment, name = "leave_comment"),
]

site1/site1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('grappelli/', include('grappelli.urls')), # grappelli URLS
	path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

site1/site1/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
	article_title = models.CharField("Назва статті", max_length = 200)
	article_text = models.TextField("Текст статті" )
	pub_date = models.DateTimeField('Дата публікації')

	def __str__(self):
		return self.article_title
	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

	class Meta:
		verbose_name = 'Стаття'
		verbose_name_plural = 'Статті'
class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField("ім'я автора", max_length = 50)
	comment_text = models.CharField('текст коментаря', max_length = 200)

	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = 'Коментар'
		verbose_name_plural = 'Коментарі'

site1/site1/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Article, Comment

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
	except:
		raise Http404("Статтю не знайдено!")

	latest_comment_list = a.comment_set.order_by('-id')[:10]
	return render(request, 'articles/detail.html', {'article': a, 'latest_comment_list': latest_comment_list})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get( id = article_id )
	except:
		raise Http404("Статтю не знайдено!")

	a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])

	return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )

def post_list(request):
    posts = Article.objects.filter(published_date=timezone.now()).order_by('published_date')
    return render(request, 'articles/list.html', {'posts': posts})

site1/site1/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{aricle.article_title}}{% endblock %}

{% block content %}

	
<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>
{% if article.was_published_recently %}
Нова стаття
{% endif %}
<hr>


{% if latest_comment_list %}
	{% for c in latest_comment_list %}
		<p>
			<strong>{{c.author_name}}</strong>
			<p>{{c.comment_text}}</p>
		</p>
		
	{% endfor %}
{% else %}
Коментарів немає!
{% endif %}


<hr>
<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

	{% csrf_token %}
	
	<input type="text" required placeholder ="Ваше ім'я" name="name"><br>
	<textarea name="text" required="" placeholder="Текст коментаря" cols="30" rows="10"></textarea><br>

	<button type="submit">Залишити коментар</button>

</form>

{% endblock %}

site1/site1/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Останні статті{% endblock %}

{% block content %}
<div>
	{% if latest_articles_list %}

		{% for a in latest_articles_list %}
		<a href=" {% url 'articles:detail' a.id %} ">{{a.article_title}}</a>
		<p>{{a.article_text}}</p>
		
</div>
		{% endfor %}

	{% else %}

	<h2>Нічого не Знайдено )=</h2>
	{% endif %}
{% endblock %}

site1/site1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
	<meta charset="utf-8">
	<div class="page-header"><title>{% block title %}Blog DS{% endblock %}</title></div>
</head>
<body>
	<div class="page-header">
    <h1><a href="/">Blog DS</a></h1>
</div>
<div class="content container">
    <div class="row">
        <div class="col-md-8">	
                <div class="post">
                    <div class="date">
	{% block content %} {% endblock %}
</div>
</div>
</div>
</div>
</div>

</body>
</html>